# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data

```{r, echo=TRUE}
library(reshape2)
library(ggplot2)
library(lattice)
act <- read.csv("activity.csv")

```


## What is mean total number of steps taken per day?

```{r, echo=TRUE}

dayact <- melt(act[ , c(1, 2)], id.vars = "date", na.rm = TRUE)
dayact2 <- dcast(dayact, date ~ variable, fun.aggregate = sum)
qplot(steps, data = dayact2)
print("mean:")
mean(dayact2$steps)
print("median")
median(dayact2$steps)

```

## What is the average daily activity pattern?
```{r, echo=TRUE}

dayact4 <- melt(act[ , c(1,3)], id.vars = "interval", na.rm = TRUE)
dayact5 <- dcast(dayact4, interval ~ variable, fun.aggregate = mean)

plot(c(1:288), dayact5$steps, type = "p")
print("interval that contains most average steps:")
print(dayact5[dayact5$steps == max(dayact5$steps), "interval"])

```


## Imputing missing values
```{r, echo=TRUE}
numNA <- nrow(act)- nrow(dayact)
print(paste("number of NAs:", numNA))
act1 <- act
 
print("Replacing missing values with the mean of its 5-minute interval")

for (i in (1 : nrow(act))) {
  if (is.na(act[i, "steps"]))
    act1[i, "steps"] <- dayact5[dayact5$interval == act1[i, "interval"], "steps"]
}

dayact6 <- melt(act1[ , c(1, 2)], id.vars = "date", na.rm = TRUE)
dayact7 <- dcast(dayact6, date ~ variable, fun.aggregate = sum)
qplot(steps, data = dayact7)
print("mean:")
mean(dayact7$steps)
print("median:")
median(dayact7$steps)

print("The resutls are different")
print("as the mean values replace the NAs, mean of the devised dataset stay unchanged, and the median changes from 10765 to 10766")

```


## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
act1$day <- weekdays(as.Date(act1$date))
act1$week <- c()
for (i in 1:nrow(act1)) {
  if (act1[i, "day"] %in% c("星期日","星期六"))
    act1[i, "week"] <- "weekend"
  else
    act1[i, "week"] <- "weekday"
}

xyplot(steps ~ interval | week, data = act1, layout = c(1, 2), type = "l")
```

